spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/tour_manager
spring.datasource.username=postgres
spring.datasource.password=postSUN2026
server.servlet.session.timeout=24h

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=sunturist.notifications@gmail.com

spring.mail.password=czma qxsg juzz kprc

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true

app.register.secret=RsunLozinka26